### ISSUE TITLE
expireAfterSeconds value written as string

### ISSUE THREAD

**Issue by Desmodue** [dottodot/prerender-mongo#2]
Hi

I am using Mongo 2.4.10.
The system.indexes expireAfterSeconds value was written as a string. This appears to stop the TTL service expiring old documents.
I had not set the environment variable for TTL at initialisation, so took the default
e.g.
{
   "v": NumberInt(1),
   "name": "createdAt_1",
   "key": {
     "createdAt": 1 
  },
   "ns": "prerender.pages",
   "expireAfterSeconds": "86400" 
}

My Fix was to drop the Index and recreate it manually in mongo shell.
{
   "v": NumberInt(1),
   "name": "createdAt_1",
   "key": {
     "createdAt": 1 
  },
   "ns": "prerender.pages",
   "expireAfterSeconds": 86400 
}
TTLMonitor immediately started removing old items.

Now this may have been totally self inflicted as I did try a few other prerender\mongo plugins. Which may have set the Index this way before as they appear closely related to this code.
May help others wondering why old records are not purged.

**Comment by dottodot** [comment]
I've just checked on my installation and it's not showing as a string so think it probably was from another plugin.

**Comment by jeromenrco** [comment]
Hi dottodot,

Same issue here. TTL is not working.

Before : 
 db.getCollection('pages').getIndexes()

       {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "prerender.pages"
        },
        {
                "v" : 1,
                "key" : {
                        "createdAt" : 1
                },
                "name" : "createdAt_1",
                "ns" : "prerender.pages",
                "expireAfterSeconds" : "60"
        }

After dropped my index, recreate it manually with this command =

db.pages.createIndex({
      "createdAt": 1
    }, {
      expireAfterSeconds: 60
    })

Results :

 db.getCollection('pages').getIndexes()

    {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "prerender.pages"
    },
    {
        "v" : 1,
        "key" : {
            "createdAt" : 1.0
        },
        "name" : "createdAt_1",
        "ns" : "prerender.pages",
        "expireAfterSeconds" : 60.0
    }

TTL is working.

**Comment by dottodot** [comment]
Ok thanks for reporting it and the pull request, it's been updated now.
